name: arquitectura-web

services:
  frontend:
    build:
      context: frontend/
    restart: always
    ports:
      - 3001:3001
    environment:
      PORT: 3001
    networks:
      - app

  backend:
    build:
      context: backend/
    restart: always
    ports:
      - 3000:3000
    environment:
      PORT: 3000
      DATABASE_HOST: database
      DATABASE_USERNAME: root
      DATABASE_PASSWORD: root
      DATABASE_NAME: stock_management
      LOG_LEVEL: 'log' # log, verbose
    networks:
      - app

  database:
    image: mariadb:lts-ubi
    restart: always
    ports:
      - 3306:3306
    environment:
      MARIADB_ROOT_PASSWORD: root
    networks:
      - app
    volumes:
      - mariadb:/var/lib/mysql/
      - ./db/schema.sql:/docker-entrypoint-initdb.d/schema.sql
  
  db-shell:
    image: mariadb:lts-ubi
    restart: unless-stopped
    networks:
      - app
    command:
      - sleep
      - infinity

networks:
  app:
    driver: bridge

volumes:
  mariadb:
    driver: local